import { writeTopics } from "../author-content.mjs";

const topics = [
  {
    id: "u1-24-economic-models",
    sourceUrl: "https://www.bankofengland.co.uk/education/education-resources",
    prerequisites: ["u1-01-economics-social-science"],
    related: ["u1-25-ppc-construction", "u1-32-logic-hypotheses-theories"],
    "zh-CN": {
      title: "经济模型的作用与局限",
      takeaway: "经济模型有意简化现实来突出关键关系；好模型不是细节最多，而是在明确假设下对问题有解释力。",
      definition: "经济模型是对现实经济主体、约束和关系的有目的简化，用文字、图形或数学表达因果机制并形成可检验预测。",
      causalChain: ["研究者提出一个具体问题", "保留被认为关键的变量和关系", "用假设隔离机制并推出预测", "把预测与证据比较后修正模型"],
      example: { title: "中央银行用模型解释政策传导", explanation: "英格兰银行的教育资料把利率、消费、投资、产出和通胀组织为简化关系。模型帮助解释传导方向，但真实效果仍取决于预期、金融状况和时滞。" },
      misconceptions: ["模型不现实的某个细节不一定使模型无用；关键是简化是否破坏所研究的机制。", "模型结论是有条件的预测，不是任何时间地点都成立的保证。"],
      examApplication: ["使用图形前先写出关键假设，并在评价时放松其中一个假设。", "说明模型能解释什么，也说明它遗漏了哪些相关变量或群体。"],
      summary: ["模型把复杂现实压缩成关键关系。", "假设决定结论的适用范围。", "预测需要证据检验和迭代。"],
      synonyms: ["经济抽象", "简化框架", "economic representation"],
      explanation: "现实经济包含太多同时变化的因素，无法一次全部分析。模型通过选择变量、设定假设和表达关系，使一个机制变得可理解。PPC、供需图和 AD–AS 都属于模型。\n\n简化带来力量也带来局限。若遗漏因素与问题无关，模型仍可有效；若遗漏因素改变结论方向，模型就需要扩展。经济学家会比较预测和证据，而不是把模型当作现实的缩小照片。",
    },
    en: {
      title: "Purposes and limits of economic models",
      takeaway: "An economic model deliberately simplifies reality to isolate important relationships; the best model is useful for a question under clear assumptions, not the one with the most detail.",
      definition: "An economic model is a purposeful simplification of agents, constraints, and relationships, expressed verbally, graphically, or mathematically to explain a mechanism and generate testable predictions.",
      causalChain: ["A researcher specifies a focused question", "Variables and relationships judged essential are retained", "Assumptions isolate a mechanism and yield predictions", "Predictions are compared with evidence and the model is revised"],
      example: { title: "A central bank models policy transmission", explanation: "Bank of England education resources organise interest rates, consumption, investment, output, and inflation into simplified relationships. The model clarifies transmission while expectations, financial conditions, and lags shape the actual effect." },
      misconceptions: ["An unrealistic detail does not automatically make a model useless; the test is whether the simplification damages the mechanism being studied.", "A model conclusion is a conditional prediction, not a guarantee for every time and place."],
      examApplication: ["State key assumptions before using a diagram, then relax one assumption in evaluation.", "Explain both what the model illuminates and which relevant variables or groups it omits."],
      summary: ["Models compress complexity into selected relationships.", "Assumptions define the range of a conclusion.", "Predictions must face evidence and revision."],
      synonyms: ["economic abstraction", "simplified framework", "economic representation"],
      explanation: "An economy contains too many changing elements to analyse simultaneously. A model selects variables, sets assumptions, and expresses relationships so that one mechanism becomes intelligible. The PPC, supply and demand, and AD–AS are all models.\n\nSimplification is both the source of power and a limitation. Omitting an irrelevant detail may be harmless; omitting a factor that changes the direction of a result is not. Economists confront predictions with evidence rather than treating a model as a miniature photograph of reality.",
    },
  },
  {
    id: "u1-25-ppc-construction",
    sourceUrl: "https://data.worldbank.org/indicator/NV.IND.TOTL.ZS",
    prerequisites: ["u1-13-factors-of-production", "u1-24-economic-models"],
    related: ["u1-26-ppc-scarcity-choice-cost", "u1-27-ppc-unemployment-efficiency"],
    diagramIds: ["ppc-core"],
    "zh-CN": {
      title: "生产可能性曲线的构造",
      takeaway: "PPC 在资源、技术和时期给定时，连接两类产出所有最大可行组合。",
      definition: "生产可能性曲线（PPC）是在既定资源、技术和充分有效利用假设下，一个经济体在两类商品或服务之间能够生产的最大组合边界。",
      causalChain: ["固定时期、资源数量与技术", "把产出归纳为横纵轴两类", "计算每种资源配置下的最大产出组合", "连接有效组合形成生产可能性边界"],
      example: { title: "把实际产业数据归纳成两类产出", explanation: "世界银行工业增加值数据展示经济体产出结构。构造教学 PPC 时可把工业与其他产出作为两轴，但必须说明这是对多产品经济的高度简化。" },
      misconceptions: ["横轴和纵轴表示产出数量，不是价格或资源投入。", "曲线位置不是固定不变；资源或技术改变会移动边界。"],
      examApplication: ["给两轴写清产品名称和单位，并在图中标注曲线。", "使用 PPC 结论前说明既定资源、既定技术和有效生产等假设。"],
      summary: ["PPC 是最大可行产出组合的边界。", "模型把多种产出简化为两类。", "曲线基于资源、技术和效率假设。"],
      synonyms: ["生产可能性边界", "PPF", "production possibility curve"],
      explanation: "PPC 通过假设经济体只生产两类产出来显示资源约束。将更多资源从一种产出转向另一种产出，可以得到一系列最大产出组合；连接这些组合就形成曲线。\n\n曲线本身代表可行集合的边界，而边界内包含未充分利用资源的组合。模型不声称现实只有两种商品，它用两轴使取舍和生产能力可视化。",
    },
    en: {
      title: "Constructing a PPC",
      takeaway: "A PPC joins the maximum feasible combinations of two output categories for a stated period, stock of resources, and technology.",
      definition: "A production possibility curve (PPC) is the boundary of maximum combinations of two goods or services that an economy can produce when resources and technology are given and resources are fully and efficiently employed.",
      causalChain: ["Fix the period, resource stock, and technology", "Aggregate output into two labelled axes", "Find maximum output under alternative resource allocations", "Join the efficient combinations to form the frontier"],
      example: { title: "Aggregating actual industry data into two outputs", explanation: "World Bank industry value-added data reveal the structure of output. A classroom PPC might place industry and other output on its axes, provided it acknowledges the substantial simplification of a multi-product economy." },
      misconceptions: ["The axes measure quantities of output, not prices or the amount of inputs.", "The frontier is not permanently fixed; changes in resources or technology shift it."],
      examApplication: ["Label both products and units and name the curve clearly.", "Before interpreting the PPC, state assumptions about given resources, technology, and efficient production."],
      summary: ["The PPC is the boundary of maximum feasible output combinations.", "It reduces many outputs to two categories.", "Its position depends on assumptions about resources, technology, and efficiency."],
      synonyms: ["production possibility frontier", "PPF", "transformation curve"],
      explanation: "The PPC displays a resource constraint by assuming that an economy produces just two categories of output. Reallocating factors from one output to the other generates a set of maximum combinations; connecting them creates the curve.\n\nThe line is the boundary of the feasible set, while combinations inside it reflect unused or inefficiently used resources. The model does not claim that an economy literally produces only two products. Two axes make trade-offs and productive capacity visible.",
    },
  },
  {
    id: "u1-26-ppc-scarcity-choice-cost",
    sourceUrl: "https://www.imf.org/en/Publications/FM",
    prerequisites: ["u1-14-opportunity-cost", "u1-25-ppc-construction"],
    related: ["u1-27-ppc-unemployment-efficiency", "u1-29-ppc-opportunity-cost-shapes"],
    diagramIds: ["ppc-core"],
    "zh-CN": {
      title: "PPC中的稀缺、选择与机会成本",
      takeaway: "PPC 外的组合体现当前稀缺，曲线上的不同点体现选择，沿曲线移动时放弃的另一种产出体现机会成本。",
      definition: "在 PPC 模型中，边界限制表示稀缺；边界上的可选组合表示选择；从一点移动到另一点所减少的另一种产出数量表示机会成本。",
      causalChain: ["资源限制形成生产边界", "社会在边界上选择一种产出组合", "增加横轴产出需要重新配置资源", "纵轴产出的减少量成为横轴产出的机会成本"],
      example: { title: "财政资源在公共目标间取舍", explanation: "IMF《财政监测》分析有限财政空间。若人员和预算都受约束，扩大一种公共服务可能需要放弃另一项支出，逻辑上可用 PPC 的沿线移动表达。" },
      misconceptions: ["曲线外的点不是永远不可能，而是在当前资源和技术下不可达。", "机会成本由放弃的产出变化衡量，不是曲线上点到点的几何距离。"],
      examApplication: ["在图上标出初始点、终点和两个方向的产量变化。", "文字解释必须把曲线位置与稀缺、选择、机会成本逐一对应。"],
      summary: ["边界体现当前生产限制。", "曲线上的多个组合迫使社会选择。", "沿边界移动显示一种产出的机会成本。"],
      synonyms: ["PPC取舍", "PPC机会成本", "production trade-off"],
      explanation: "PPC 把抽象的稀缺转化为可见边界。曲线外的组合超过当前能力，因此不能同时实现；曲线上的组合都可行且有效，但社会只能选择其中一个。\n\n沿曲线增加一种产出需要把资源从另一种生产转出。另一种产出的减少就是新增产出的机会成本。回答时要同时写出数量方向与经济含义。",
    },
    en: {
      title: "Scarcity, choice, and cost on a PPC",
      takeaway: "Points beyond a PPC reveal current scarcity, alternative points on the line represent choice, and movement along it reveals the other output forgone as opportunity cost.",
      definition: "Within the PPC model, the frontier represents scarcity, alternative feasible combinations represent choice, and the reduction in one output when moving along the curve measures the opportunity cost of more of the other.",
      causalChain: ["Resource constraints create a production boundary", "Society selects one combination on the boundary", "More horizontal-axis output requires reallocation", "The lost vertical-axis output is its opportunity cost"],
      example: { title: "Fiscal resources trade off across public objectives", explanation: "The IMF Fiscal Monitor examines limited fiscal space. Where budgets and administrative capacity are constrained, expanding one public service may require less of another, a logic represented by movement along a PPC." },
      misconceptions: ["A point outside the curve is not impossible forever; it is unattainable with current resources and technology.", "Opportunity cost is measured by forgone output, not by the geometric distance between two points."],
      examApplication: ["Mark the starting point, destination, and quantity changes in both directions.", "Link frontier position separately to scarcity, choice, and opportunity cost in the written explanation."],
      summary: ["The frontier displays a current productive constraint.", "Multiple combinations on the line require choice.", "Movement along the frontier reveals the cost in the other output."],
      synonyms: ["PPC trade-off", "PPC opportunity cost", "production trade-off"],
      explanation: "The PPC turns abstract scarcity into a visible boundary. A combination beyond the curve exceeds current capacity and cannot be produced now. Every point on the curve is feasible and efficient, but society must select one of them.\n\nMore of one output along the curve requires resources to leave production of the other. The fall in that second output is the opportunity cost of the increase. A complete answer states both quantity directions and their economic meaning.",
    },
  },
  {
    id: "u1-27-ppc-unemployment-efficiency",
    sourceUrl: "https://ilostat.ilo.org/topics/unemployment-and-labour-underutilization/",
    prerequisites: ["u1-25-ppc-construction"],
    related: ["u1-06-efficiency", "u1-28-ppc-growth"],
    diagramIds: ["ppc-core"],
    "zh-CN": {
      title: "PPC中的失业与生产效率",
      takeaway: "曲线内点表示当前能力未被充分或有效使用，曲线上点表示生产效率；回到边界可增加一种或两种产出。",
      definition: "PPC 内部的点代表失业、闲置或低效配置使实际产出低于最大可能；曲线上的点代表既定资源和技术下的生产效率。",
      causalChain: ["部分劳动或资本闲置或错配", "实际产出落在生产边界以内", "需求恢复、再培训或管理改善提高利用率", "经济体移向边界并实现实际增长"],
      example: { title: "劳动未充分利用限制实际产出", explanation: "国际劳工组织 ILOSTAT 区分失业和更广泛的劳动未充分利用。可用劳动没有进入有效生产时，经济体可能在其现有生产能力以内运行。" },
      misconceptions: ["边界内点不一定只由失业造成，设备闲置和资源错配也可能导致低效率。", "曲线上所有点都具有生产效率，但未必具有配置效率。"],
      examApplication: ["用从曲线内到曲线上的箭头表示资源利用改善。", "区分这种实际产出增加与曲线向外移动的潜在增长。"],
      summary: ["曲线内表示未充分利用或低效。", "曲线上表示生产效率。", "向边界移动不要求生产能力本身扩大。"],
      synonyms: ["PPC失业", "生产低效", "inside the PPC"],
      explanation: "如果劳动失业、机器闲置或资源配置不当，经济体可以生产更多至少一种产品而不减少另一种，因此实际组合位于边界以内。\n\n消除闲置或改善组织会把产出推向曲线。这个过程使用原有能力，属于实际增长或复苏。达到曲线只说明投入得到有效利用，不说明社会选择了最想要的产品组合。",
    },
    en: {
      title: "Unemployment and efficiency on a PPC",
      takeaway: "A point inside the PPC indicates that current capacity is underused or used inefficiently; a point on the line is productively efficient, and returning to it can raise one or both outputs.",
      definition: "A point inside a PPC represents actual output below the feasible maximum because of unemployment, idle capacity, or inefficient allocation, while a point on the curve represents productive efficiency for the given resources and technology.",
      causalChain: ["Some labour or capital is idle or mismatched", "Actual output lies within the production boundary", "Recovery, retraining, or better management raises utilisation", "The economy moves toward the frontier and actual output grows"],
      example: { title: "Labour underutilisation restricts actual output", explanation: "ILOSTAT distinguishes unemployment from broader labour underutilisation. When available labour is not engaged in effective production, an economy may operate inside its existing productive capacity." },
      misconceptions: ["An interior point is not caused only by unemployment; idle equipment and misallocation can also create inefficiency.", "Every point on the PPC is productively efficient but not necessarily allocatively efficient."],
      examApplication: ["Use an arrow from inside the curve to the boundary to show improved resource use.", "Distinguish this rise in actual output from an outward shift representing greater potential."],
      summary: ["Inside the curve indicates underuse or inefficiency.", "On the curve indicates productive efficiency.", "Moving to the frontier does not require capacity itself to expand."],
      synonyms: ["PPC unemployment", "productive inefficiency", "inside the PPC"],
      explanation: "With unemployed labour, idle machinery, or poor resource allocation, at least one output can rise without reducing the other. The actual combination therefore lies within the frontier.\n\nUsing idle factors or improving organisation moves output toward the curve. This is growth in actual production or recovery using existing capacity. Reaching the curve establishes productive efficiency, not that society has selected its preferred output mix.",
    },
  },
  {
    id: "u1-28-ppc-growth",
    sourceUrl: "https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG",
    prerequisites: ["u1-25-ppc-construction", "u1-27-ppc-unemployment-efficiency"],
    related: ["u1-10-change", "u1-13-factors-of-production"],
    diagramIds: ["ppc-core"],
    "zh-CN": {
      title: "实际增长与生产潜力增长",
      takeaway: "向既有 PPC 靠近是实际产出增长，PPC 向外移动是生产潜力增长；两者可发生在不同时间。",
      definition: "实际增长是经济体在既有生产能力内提高当前产出；生产可能性增长是资源数量、质量或技术改善使最大可行产出边界向外移动。",
      causalChain: ["经济体可能先在边界以内运行", "更高资源利用率使实际点靠近边界", "投资、教育、资源发现或技术进步扩大能力", "PPC 向外移动并允许更高长期产出"],
      example: { title: "增长率不能单独区分复苏与能力扩张", explanation: "世界银行实际 GDP 增长数据记录产出变化。衰退后增长可能主要来自闲置资源重新使用；持续投资与生产率提升才更可能扩大长期生产边界。" },
      misconceptions: ["实际 GDP 上升不一定表示 PPC 已向外移动。", "外移可以偏向一种产品，不必始终平行移动。"],
      examApplication: ["用点的移动表示实际增长，用曲线移动表示潜在增长。", "把资源、资本、人力资本或技术变化与曲线外移的方向联系起来。"],
      summary: ["边界内向边界移动表示利用率提高。", "边界外移表示最大能力扩大。", "增长来源决定曲线是否偏向某一轴移动。"],
      synonyms: ["实际产出增长", "潜在增长", "PPC外移"],
      explanation: "经济体低于充分能力时，可以通过提高就业和设备利用率增加产出而不改变 PPC。这通常出现在经济复苏阶段。\n\n若劳动力增加、技能提高、资本积累或技术进步，最大可行组合会扩大，PPC 向外移动。若进步只适用于某一行业，外移可能只明显发生在对应轴的一端。",
    },
    en: {
      title: "Actual and potential growth",
      takeaway: "Movement toward an existing PPC is growth in actual output, while an outward shift is growth in productive potential; the two can occur at different times.",
      definition: "Actual growth is an increase in current output within existing capacity. Growth in production possibilities is an outward shift of the maximum feasible boundary caused by more or better resources or improved technology.",
      causalChain: ["The economy may initially operate inside its frontier", "Higher utilisation moves actual output toward the line", "Investment, education, resource discovery, or technology expands capacity", "The PPC shifts outward and permits greater long-run output"],
      example: { title: "A growth rate alone cannot separate recovery from capacity expansion", explanation: "World Bank real GDP growth data record changes in output. Growth after recession may mainly reuse idle factors, whereas sustained investment and productivity improvement are more likely to expand the long-run frontier." },
      misconceptions: ["A rise in actual GDP does not by itself show that the PPC has shifted outward.", "An outward shift can be biased toward one good rather than parallel."],
      examApplication: ["Use movement of a point for actual growth and movement of the curve for potential growth.", "Connect changes in resources, physical or human capital, and technology to the direction of the shift."],
      summary: ["Movement from inside toward the frontier raises utilisation.", "An outward shift expands maximum capacity.", "The source of growth determines whether the shift favours one axis."],
      synonyms: ["growth in actual output", "potential growth", "outward PPC shift"],
      explanation: "When an economy operates below full capacity, output can rise through higher employment and capital utilisation without changing the PPC. This pattern often describes a recovery.\n\nA larger or more skilled workforce, capital accumulation, resource discovery, or technological progress expands the feasible set and shifts the PPC outward. Innovation confined to one sector can create a rotation or an uneven shift rather than a parallel movement.",
    },
  },
  {
    id: "u1-29-ppc-opportunity-cost-shapes",
    sourceUrl: "https://www.fao.org/faostat/en/#data/RL",
    prerequisites: ["u1-14-opportunity-cost", "u1-26-ppc-scarcity-choice-cost"],
    related: ["u1-13-factors-of-production", "u1-25-ppc-construction"],
    diagramIds: ["ppc-core"],
    "zh-CN": {
      title: "递增与不变机会成本",
      takeaway: "专业化资源使 PPC 通常向外弯并呈递增机会成本；资源同质且可完全替代时，直线 PPC 表示不变机会成本。",
      definition: "递增机会成本是连续增加一种产出时每个新增单位需放弃越来越多另一种产出；不变机会成本则表示交换比率保持相同。",
      causalChain: ["资源对两种生产的适用程度不同", "先转移最适合新增产品的资源", "继续扩大时必须转移越来越不适合的资源", "每个新增单位造成更大的另一种产出损失"],
      example: { title: "土地用途具有不同适宜性", explanation: "FAOSTAT 土地利用资料区分耕地、牧场等用途。土地的土壤、气候和位置不同，持续把更多土地转向某作物时，较不适宜土地会带来更高机会成本。" },
      misconceptions: ["向外弯曲描述机会成本变化，不表示经济增长。", "斜率为负表示取舍；比较机会成本时看斜率绝对值。"],
      examApplication: ["用资源异质性解释递增机会成本，而不要只写‘曲线弯曲’。", "从坐标变化计算一段 PPC 的机会成本，并写明单位。"],
      summary: ["异质和专业化资源导致递增成本。", "同质可替代资源可产生不变成本。", "PPC 斜率的绝对值反映机会成本。"],
      synonyms: ["递增机会成本规律", "直线PPC", "凹向原点PPC"],
      explanation: "生产要素通常不是对所有用途同样有效。扩大一种产品时，最适合该产品的资源会先被转移；再扩大就要使用更适合另一种产品的资源，因此放弃量递增。\n\n若资源在两种用途间生产率比例完全相同，每转移一单位资源造成的取舍相同，PPC 就是一条直线。这是有用基准，但现实中资源专用性更常见。",
    },
    en: {
      title: "Increasing and constant opportunity cost",
      takeaway: "Specialised resources normally create a bowed-out PPC and increasing opportunity cost; identical, perfectly transferable resources create a straight line and constant cost.",
      definition: "Increasing opportunity cost means that successive additions to one output require ever larger reductions in the other, while constant opportunity cost means that the trade-off ratio does not change.",
      causalChain: ["Resources differ in suitability for the two outputs", "Resources best suited to the expanding good move first", "Further expansion transfers increasingly unsuitable factors", "Each extra unit requires a larger loss of the other output"],
      example: { title: "Land differs in its suitability for alternative uses", explanation: "FAOSTAT land-use data distinguish arable land, pasture, and other uses. Soil, climate, and location differ, so moving progressively more land toward one crop is likely to involve rising opportunity cost." },
      misconceptions: ["A bowed shape describes changing opportunity cost, not economic growth.", "The negative slope displays a trade-off; its absolute value is used when comparing opportunity cost."],
      examApplication: ["Explain increasing cost through heterogeneous resources rather than merely saying the curve is bowed.", "Calculate opportunity cost from coordinate changes and include units."],
      summary: ["Heterogeneous and specialised resources generate increasing cost.", "Homogeneous transferable resources can generate constant cost.", "The absolute slope of a PPC reflects opportunity cost."],
      synonyms: ["law of increasing opportunity cost", "linear PPC", "bowed-out PPC"],
      explanation: "Factors of production are rarely equally productive in every use. Expansion of one good first draws resources well suited to it; further expansion requires resources with stronger productivity in the other activity, so the forgone amount rises.\n\nIf every resource has the same productivity ratio in both uses, each transfer creates the same trade-off and the PPC is a straight line. That case is a useful benchmark, while resource specificity is more common in practice.",
    },
  },
];

writeTopics(topics);
