import { writeTopics } from "../author-content.mjs";

const topics = [
  {
    id: "u1-36-adam-smith",
    sourceUrl: "https://www.econlib.org/library/Enc/bios/Smith.html",
    prerequisites: ["u1-19-market-mechanism", "u1-21-free-market-economy"],
    related: ["u1-37-utility-marginalism", "u1-38-says-law"],
    "zh-CN": {
      title: "亚当·斯密与自由放任",
      takeaway: "斯密强调分工、交换和竞争如何协调自利行为，但其论述并非主张完全没有法律、公共品或道德约束。",
      definition: "亚当·斯密的古典经济思想把专业化、市场交换和竞争视为财富增长的重要来源；自由放任指政府避免不必要地替代分散市场决定。",
      causalChain: ["分工提高劳动专门化和熟练度", "交换使专业化产出能够互换", "价格与利润协调分散选择", "竞争限制部分私人权力并推动适应"],
      example: { title: "分工仍是现代生产网络的基础", explanation: "Econlib 的斯密传记介绍其关于分工、交换和制度的思想。现代供应链把任务分配给专门企业，体现生产率收益，也暴露协调与依赖风险。" },
      misconceptions: ["“看不见的手”不是任何市场结果都完美的保证。", "斯密承认司法、国防、公共工程和教育等国家职能，并非主张取消政府。"],
      examApplication: ["把分工—生产率—交换—市场扩大的逻辑链写完整。", "评价自由放任时同时讨论竞争条件、公共品、外部性和市场权力。"],
      summary: ["分工和交换支持生产率与财富增长。", "价格和竞争协调分散决定。", "市场运作仍依赖制度与公共职能。"],
      synonyms: ["古典自由主义", "看不见的手", "laissez-faire"],
      explanation: "斯密观察到分工可以通过熟练度、节省转换时间和促进工具创新提高产量。只要人们能够交换，生产者就可以专门化，并通过市场获得其他商品。\n\n自由放任更适合被理解为对不必要管制和特权的怀疑，而非无政府状态。产权、合同、竞争和公共基础设施使市场协调成为可能；垄断和权力集中则会削弱其效果。",
    },
    en: {
      title: "Adam Smith and laissez-faire",
      takeaway: "Smith explained how specialisation, exchange, and competition can coordinate self-interested action, without arguing that law, public goods, or moral constraints are unnecessary.",
      definition: "Adam Smith's classical economics treated specialisation, market exchange, and competition as important sources of growing wealth. Laissez-faire favours avoiding unnecessary state replacement of decentralised market decisions.",
      causalChain: ["Division of labour increases specialisation and skill", "Exchange allows specialised outputs to be traded", "Prices and profit coordinate decentralised choices", "Competition constrains some private power and encourages adaptation"],
      example: { title: "Division of labour remains central to production networks", explanation: "The Econlib biography of Smith introduces his thinking on specialisation, exchange, and institutions. Modern supply chains divide tasks across expert firms, gaining productivity while also creating coordination and dependency risks." },
      misconceptions: ["The invisible hand is not a guarantee that every market outcome is ideal.", "Smith recognised roles for justice, defence, public works, and education; he did not propose abolishing government."],
      examApplication: ["Complete the chain from specialisation to productivity, exchange, and a wider market.", "Evaluation of laissez-faire should address competition, public goods, externalities, and market power."],
      summary: ["Specialisation and exchange support productivity and wealth.", "Price and competition coordinate decentralised choices.", "Markets still depend on institutions and public functions."],
      synonyms: ["classical liberalism", "invisible hand", "laissez-faire"],
      explanation: "Smith argued that division of labour raises output through dexterity, reduced switching time, and invention of tools. Exchange then lets producers specialise while obtaining other goods through a market.\n\nLaissez-faire is better understood as scepticism toward unnecessary controls and privileges than as the absence of the state. Property, contracts, competition, and public infrastructure enable coordination, while monopoly and concentrated power can undermine it.",
    },
  },
  {
    id: "u1-37-utility-marginalism",
    sourceUrl: "https://www.econlib.org/library/Enc/Marginalism.html",
    prerequisites: ["u1-02-microeconomics"],
    related: ["u1-36-adam-smith", "u1-42-behavioural-economics"],
    "zh-CN": {
      title: "效用理论与边际主义",
      takeaway: "边际主义用“再增加一单位”带来的收益和成本解释选择，推动价值理论从总量与生产成本转向边际评价。",
      definition: "效用理论把消费满足作为选择依据；边际主义关注一个变量微小增加所带来的额外效用、产出或成本，并以边际比较解释决策。",
      causalChain: ["经济主体已经拥有一定数量", "额外一单位带来边际收益或效用", "获得该单位也产生边际成本", "主体比较两者并调整直到继续改变不再有利"],
      example: { title: "用边际思维解释用水优先顺序", explanation: "Econlib 对边际主义的介绍说明价值取决于额外单位的用途。水的总价值极高，但供应充足时新增一单位可能用于较低优先级用途，因此边际价值较低。" },
      misconceptions: ["边际不等于微不足道，而是指变化中的额外一单位。", "总效用高并不意味着最后一单位的边际效用也高。"],
      examApplication: ["用边际收益与边际成本解释选择何时停止。", "区分总量、平均量和边际量，写明所比较的新增单位。"],
      summary: ["选择发生在边际。", "边际效用通常随消费增加而下降。", "最优调整取决于边际收益与边际成本的比较。"],
      synonyms: ["边际革命", "边际效用", "marginal analysis"],
      explanation: "古典价值解释较强调生产成本。十九世纪边际主义者指出，实际选择取决于下一个单位能带来的用途与满足，而不是所有单位的总价值。\n\n边际分析成为现代微观经济学的重要方法。消费者比较额外消费的收益和价格，企业比较额外产出的收入和成本。它不要求变化真的无限小，而要求关注选择边缘。",
    },
    en: {
      title: "Utility theory and marginalism",
      takeaway: "Marginalism explains choice through the benefit and cost of one more unit, shifting value theory from totals and production cost toward evaluation at the margin.",
      definition: "Utility theory treats satisfaction from consumption as a basis for choice. Marginalism studies the extra utility, output, or cost created by a small increase and explains decisions through marginal comparison.",
      causalChain: ["An agent already holds or produces some quantity", "One more unit creates a marginal benefit or utility", "Obtaining that unit also creates marginal cost", "The agent adjusts until a further change no longer improves the objective"],
      example: { title: "Marginal thinking explains priorities for water use", explanation: "The Econlib account of marginalism explains that value depends on the use of an additional unit. Water has enormous total value, yet when supply is abundant, the next unit may serve a low-priority use and carry a low marginal value." },
      misconceptions: ["Marginal does not mean unimportant; it means the additional unit involved in a change.", "High total utility does not imply high marginal utility from the final unit."],
      examApplication: ["Use marginal benefit and marginal cost to explain where adjustment stops.", "Distinguish total, average, and marginal values and identify the additional unit being compared."],
      summary: ["Choice takes place at the margin.", "Marginal utility commonly falls as consumption rises.", "Optimal adjustment depends on marginal benefit relative to marginal cost."],
      synonyms: ["marginal revolution", "marginal utility", "marginal analysis"],
      explanation: "Classical accounts of value placed substantial weight on production cost. Nineteenth-century marginalists argued that an actual choice depends on the use and satisfaction available from the next unit rather than the total value of all units.\n\nMarginal analysis became a central method in modern microeconomics. Consumers compare the benefit of extra consumption with price, and firms compare extra revenue with extra cost. The change need not be literally infinitesimal; the focus is the decision edge.",
    },
  },
  {
    id: "u1-38-says-law",
    sourceUrl: "https://www.econlib.org/library/Enc/SaysLaw.html",
    prerequisites: ["u1-36-adam-smith"],
    related: ["u1-40-keynesian-revolution", "u1-41-monetarist-new-classical"],
    "zh-CN": {
      title: "萨伊定律",
      takeaway: "萨伊定律强调生产创造收入并支持需求，因而怀疑普遍长期供给过剩；凯恩斯后来挑战了这一自我调整结论。",
      definition: "萨伊定律通常概括为供给创造相应需求：生产过程产生收入，使总体购买力能够吸收产出，因此全面持久的总需求不足不应在灵活市场中持续。",
      causalChain: ["企业生产并支付工资、租金与利润", "这些要素收入形成购买力", "收入用于消费、储蓄或投资融资", "价格和利率调整使总体供求重新协调"],
      example: { title: "经济衰退检验自我调整速度", explanation: "Econlib 对萨伊定律的介绍讨论生产与需求的联系。严重衰退中收入可能被持有而投资不响应，这成为凯恩斯质疑自动恢复机制的关键。" },
      misconceptions: ["该命题不声称每一种商品都能自动售出，个别市场仍会供过于求。", "‘供给创造需求’不是同一企业购买自己产品，而是生产创造要素收入。"],
      examApplication: ["先说明生产—收入—支出的循环机制，再讨论储蓄、预期和价格刚性。", "与凯恩斯观点比较时聚焦总需求不足能否持续。"],
      summary: ["生产创造收入和潜在购买力。", "古典框架依赖价格与利率调整。", "储蓄不转化为投资时自我调整可能受阻。"],
      synonyms: ["供给创造需求", "市场定律", "Say law"],
      explanation: "萨伊定律来自古典经济学对生产和收入循环的强调。生产商品时也向劳动者和资源所有者支付收入，因此总供给同时创造了购买力来源。\n\n争议集中在收入是否一定及时转化为支出。若储蓄通过利率变化流向投资，全面过剩难以持续；若不确定性使储蓄增加而投资疲弱，总需求可能低于充分就业产出。",
    },
    en: {
      title: "Say's Law",
      takeaway: "Say's Law emphasises that production creates income and supports demand, casting doubt on a persistent general glut; Keynes later challenged the speed and reliability of that adjustment.",
      definition: "Say's Law is commonly summarised as supply creating corresponding demand: production generates income, giving the economy purchasing power to absorb output, so broad and lasting deficient demand should not persist in flexible markets.",
      causalChain: ["Firms produce and pay wages, rent, and profit", "Factor incomes create purchasing power", "Income funds consumption or saving that can finance investment", "Price and interest-rate adjustment recoordinates aggregate supply and demand"],
      example: { title: "Recession tests the speed of self-correction", explanation: "The Econlib discussion of Say's Law presents the link between production and demand. In a severe downturn, income may be hoarded while investment fails to respond, forming a central part of Keynes's objection to automatic recovery." },
      misconceptions: ["The proposition does not mean every particular product must sell; individual markets can have excess supply.", "Supply creates demand through factor income, not because a producer buys its own product."],
      examApplication: ["Explain the production-income-spending cycle before discussing saving, expectations, and sticky prices.", "A comparison with Keynes should focus on whether deficient aggregate demand can persist."],
      summary: ["Production generates income and potential purchasing power.", "The classical account relies on price and interest-rate adjustment.", "Self-correction can fail when saving does not become investment."],
      synonyms: ["supply creates demand", "law of markets", "Say law"],
      explanation: "Say's Law emerges from the classical emphasis on the circular connection between production and income. Producing goods also pays income to workers and resource owners, so aggregate supply creates the source of purchasing power.\n\nThe dispute concerns whether that income reliably returns as expenditure. If interest-rate adjustment channels saving into investment, a general glut should be temporary. If uncertainty raises saving while investment remains weak, aggregate demand can fall below full-employment output.",
    },
  },
  {
    id: "u1-39-marxist-critique",
    sourceUrl: "https://plato.stanford.edu/entries/marx/",
    prerequisites: ["u1-18-income-distribution", "u1-21-free-market-economy"],
    related: ["u1-36-adam-smith", "u1-40-keynesian-revolution"],
    "zh-CN": {
      title: "马克思主义批判",
      takeaway: "马克思主义分析把所有权、阶级关系和资本积累置于核心，质疑市场交换表面的自由是否掩盖生产权力与分配冲突。",
      definition: "马克思主义经济批判以生产资料所有权、劳动与资本的阶级关系、剩余价值和资本积累为框架，分析资本主义的分配、权力与危机倾向。",
      causalChain: ["生产资料集中在资本所有者手中", "无产者出售劳动力获得工资", "产出价值与工资之间形成剩余并被积累", "积累改变权力、技术、分配并可能加剧冲突"],
      example: { title: "平台劳动重新提出控制与剩余问题", explanation: "斯坦福哲学百科的马克思条目概述异化、阶级和历史分析。数字平台中算法控制、资产所有和劳动收入的关系，可用这些问题意识研究，但具体结论仍需现代证据。" },
      misconceptions: ["马克思主义批判不只是主张收入平均，它首先分析生产关系和所有权。", "历史理论不能直接替代对当代企业、劳动市场和制度的实证研究。"],
      examApplication: ["把所有权—劳动过程—剩余—积累的机制写清。", "评价时比较其对权力和分配的洞察与预测、制度多样性和历史证据。"],
      summary: ["所有权结构影响生产与分配权力。", "剩余和积累是分析核心。", "阶级框架强调市场交换背后的生产关系。"],
      synonyms: ["马克思经济学", "阶级分析", "剩余价值理论"],
      explanation: "马克思把资本主义视为一种历史生产方式，而不只是独立买卖的集合。劳动者不拥有主要生产资料，因此通过出售劳动力参与生产；资本所有者控制投资与剩余使用。\n\n该框架强调技术变化、企业集中和危机与积累过程的联系。应用时需要区分分析概念、历史预测和规范主张，并用当代制度和数据检验哪些机制仍有解释力。",
    },
    en: {
      title: "The Marxist critique",
      takeaway: "Marxist analysis centres ownership, class relations, and capital accumulation, questioning whether formal freedom in exchange conceals power and distributional conflict in production.",
      definition: "The Marxist critique uses ownership of the means of production, class relations between labour and capital, surplus value, and accumulation to analyse distribution, power, and tendencies toward crisis in capitalism.",
      causalChain: ["Ownership of productive assets is concentrated among capital owners", "Workers sell labour power for wages", "A surplus between output and labour compensation is accumulated", "Accumulation changes power, technology, distribution, and potential conflict"],
      example: { title: "Platform work renews questions about control and surplus", explanation: "The Stanford Encyclopedia of Philosophy entry on Marx outlines alienation, class, and historical analysis. Algorithmic control, asset ownership, and labour income in digital platforms can be studied through those questions, while modern evidence remains necessary." },
      misconceptions: ["Marxist critique is not merely a demand for equal income; it begins with production relations and ownership.", "A historical theory cannot substitute directly for empirical study of current firms, labour markets, and institutions."],
      examApplication: ["Make the mechanism from ownership through labour, surplus, and accumulation explicit.", "Evaluate insights about power and distribution against predictions, institutional diversity, and historical evidence."],
      summary: ["Ownership structures influence power in production and distribution.", "Surplus and accumulation are central analytical ideas.", "Class analysis looks behind exchange to production relations."],
      synonyms: ["Marxian economics", "class analysis", "surplus value theory"],
      explanation: "Marx treated capitalism as a historical mode of production, not simply a collection of voluntary trades. Workers lack ownership of the main productive assets and participate by selling labour power, while capital owners control investment and the use of surplus.\n\nThe framework connects technological change, concentration, and crisis to accumulation. Application should separate analytical concepts, historical predictions, and normative positions and test which mechanisms retain explanatory value in contemporary institutions.",
    },
  },
  {
    id: "u1-40-keynesian-revolution",
    sourceUrl: "https://www.imf.org/external/pubs/ft/fandd/basics/keynes.htm",
    prerequisites: ["u1-03-macroeconomics", "u1-38-says-law"],
    related: ["u1-41-monetarist-new-classical"],
    "zh-CN": {
      title: "凯恩斯革命与宏观政策",
      takeaway: "凯恩斯指出总需求不足可使经济长期低于充分就业，并由此奠定用财政和货币政策稳定宏观经济的框架。",
      definition: "凯恩斯主义认为支出、预期和价格工资刚性会决定短期产出与就业；当私人需求不足且自我调整缓慢时，公共政策可支持总需求。",
      causalChain: ["悲观预期减少消费或投资", "总需求下降使企业减产和裁员", "收入下降进一步压低支出", "逆周期财政或货币政策尝试打破收缩循环"],
      example: { title: "衰退中的逆周期稳定政策", explanation: "IMF 对凯恩斯经济学的介绍说明，经济低迷时政府支出或减税可支撑需求，繁荣时则应重建财政空间；具体乘数取决于闲置资源、开放度和政策设计。" },
      misconceptions: ["凯恩斯主义不主张任何时期都扩大赤字，而强调逆周期管理。", "增加支出不会机械地产生固定乘数，挤出、进口和预期会改变效果。"],
      examApplication: ["用总需求—产出—就业—收入反馈解释衰退。", "评价稳定政策时讨论经济余量、乘数、时滞、债务和退出策略。"],
      summary: ["总需求可以持续低于充分就业水平。", "工资价格刚性减慢自我调整。", "宏观政策可稳定支出但受到条件约束。"],
      synonyms: ["凯恩斯主义", "有效需求", "需求管理"],
      explanation: "大萧条挑战了市场会迅速恢复充分就业的古典观点。凯恩斯强调企业投资取决于不确定的预期，家庭收入下降又会减少消费，使需求不足自我强化。\n\n这套思想推动宏观经济学和稳定政策形成。政府预算、自动稳定器与中央银行政策被用于缓和周期，但政策时机、融资、通胀风险和长期供给仍需要权衡。",
    },
    en: {
      title: "The Keynesian revolution and macroeconomic policy",
      takeaway: "Keynes argued that deficient aggregate demand can keep an economy below full employment, establishing a framework for fiscal and monetary stabilisation policy.",
      definition: "Keynesian economics holds that expenditure, expectations, and wage-price rigidity influence short-run output and employment, and that public policy can support aggregate demand when private demand is weak and self-correction is slow.",
      causalChain: ["Pessimistic expectations reduce consumption or investment", "Lower aggregate demand causes firms to cut output and jobs", "Falling income further reduces expenditure", "Countercyclical fiscal or monetary policy seeks to interrupt the contraction"],
      example: { title: "Countercyclical stabilisation in a downturn", explanation: "The IMF introduction to Keynesian economics describes how public spending or tax reductions can support demand in a slump and why fiscal space should be rebuilt in stronger periods. The multiplier varies with slack, openness, and policy design." },
      misconceptions: ["Keynesian policy does not prescribe larger deficits in every period; it is countercyclical.", "Additional spending does not produce a mechanically fixed multiplier because crowding out, imports, and expectations alter the effect."],
      examApplication: ["Explain recession through feedback among aggregate demand, output, employment, and income.", "Evaluate stabilisation through economic slack, the multiplier, time lags, debt, and an exit strategy."],
      summary: ["Aggregate demand can remain below full-employment output.", "Sticky wages and prices slow self-correction.", "Macroeconomic policy can stabilise spending under important conditions."],
      synonyms: ["Keynesianism", "effective demand", "demand management"],
      explanation: "The Great Depression challenged the classical expectation of rapid return to full employment. Keynes emphasised that business investment depends on uncertain expectations and that lower household income reduces consumption, allowing deficient demand to reinforce itself.\n\nThe argument helped establish macroeconomics and stabilisation policy. Government budgets, automatic stabilisers, and central-bank action can moderate a cycle, while timing, financing, inflation risk, and long-run supply still require evaluation.",
    },
  },
  {
    id: "u1-41-monetarist-new-classical",
    sourceUrl: "https://www.imf.org/external/pubs/ft/fandd/basics/monetarism.htm",
    prerequisites: ["u1-40-keynesian-revolution"],
    related: ["u1-03-macroeconomics", "u1-33-ceteris-paribus"],
    "zh-CN": {
      title: "货币主义与新古典反革命",
      takeaway: "货币主义和新古典理论重新强调货币稳定、市场调整、预期与政策可信度，并质疑积极需求管理能否持续提高实际产出。",
      definition: "货币主义强调货币供给与名义支出及通胀的长期关系；新古典宏观理论加入理性预期和市场出清，分析可预见政策为何可能被主体行为抵消。",
      causalChain: ["政策改变货币或总需求路径", "家庭和企业形成对通胀与政策的预期", "工资、价格和资产选择随预期调整", "长期影响更多体现为物价而非持续更高实际产出"],
      example: { title: "中央银行把通胀预期纳入政策", explanation: "IMF 对货币主义的介绍强调货币增长和通胀的长期联系。现代央行会关注政策可信度与预期，因为预期可提前影响工资谈判、定价和金融条件。" },
      misconceptions: ["货币主义不等于认为货币在所有时期以固定速度影响经济。", "理性预期并不表示人能完美预测，而是不会系统性忽略可用信息。"],
      examApplication: ["比较凯恩斯与货币主义时区分短期非中性和长期名义影响。", "评价规则与酌情政策时讨论信息、时滞、可信度和意外冲击。"],
      summary: ["长期通胀与货币和名义需求有关。", "预期会改变政策传导。", "可预见需求政策难以永久提高实际产出。"],
      synonyms: ["货币主义", "新古典宏观", "理性预期"],
      explanation: "二十世纪后期的货币主义者批评对财政微调和稳定乘数的过度信赖，强调政策时滞与货币稳定。新古典理论进一步分析理性预期如何使人提前调整。\n\n这些观点推动独立中央银行、通胀目标和规则可信度的讨论。现实政策通常综合多种思想：承认短期需求波动，同时重视通胀预期、供给约束和长期可持续性。",
    },
    en: {
      title: "The monetarist and new classical counter-revolution",
      takeaway: "Monetarist and new classical thinking renewed emphasis on monetary stability, market adjustment, expectations, and policy credibility, questioning whether activist demand management can raise real output persistently.",
      definition: "Monetarism stresses the long-run relationship between money growth, nominal spending, and inflation. New classical macroeconomics adds rational expectations and market clearing to examine why predictable policy may be offset by agents' responses.",
      causalChain: ["Policy changes the path of money or aggregate demand", "Households and firms form expectations about inflation and policy", "Wages, prices, and asset choices adjust to those expectations", "Long-run effects appear more in prices than in permanently higher real output"],
      example: { title: "Central banks incorporate inflation expectations", explanation: "The IMF account of monetarism emphasises the long-run connection between monetary growth and inflation. Modern central banks monitor credibility and expectations because they influence wage bargaining, pricing, and financial conditions in advance." },
      misconceptions: ["Monetarism does not claim that money affects the economy with an identical speed in every period.", "Rational expectations do not mean perfect prediction; they imply that available information is not ignored systematically."],
      examApplication: ["When comparing Keynesian and monetarist views, distinguish short-run non-neutrality from long-run nominal effects.", "Evaluate rules and discretion through information, lags, credibility, and unexpected shocks."],
      summary: ["Long-run inflation is linked to money and nominal demand.", "Expectations alter policy transmission.", "Predictable demand policy cannot permanently raise real output."],
      synonyms: ["monetarism", "new classical macroeconomics", "rational expectations"],
      explanation: "Late twentieth-century monetarists criticised excessive confidence in fiscal fine-tuning and stable multipliers, drawing attention to policy lags and monetary stability. New classical models developed the role of forward-looking expectations.\n\nThese ideas shaped debates over independent central banks, inflation targets, and credible rules. Actual policymaking often combines traditions: it accepts short-run demand fluctuations while taking inflation expectations, supply constraints, and long-run sustainability seriously.",
    },
  },
  {
    id: "u1-42-behavioural-economics",
    sourceUrl: "https://www.nobelprize.org/prizes/economic-sciences/2017/press-release/",
    prerequisites: ["u1-02-microeconomics", "u1-37-utility-marginalism"],
    related: ["u1-12-intervention", "u1-24-economic-models"],
    "zh-CN": {
      title: "行为经济学",
      takeaway: "行为经济学把有限理性、自我控制和社会偏好纳入模型，解释现实选择为何系统性偏离完全理性基准。",
      definition: "行为经济学结合心理学和经济学，研究启发式、偏差、有限注意、自我控制问题与社会偏好如何影响经济决策。",
      causalChain: ["决策者面对复杂信息和认知限制", "使用简化规则并受呈现方式影响", "实际选择偏离标准理性模型", "行为证据推动更真实的模型和政策设计"],
      example: { title: "默认选项改变参与行为", explanation: "2017 年诺贝尔经济学奖资料总结 Richard Thaler 对有限理性、社会偏好和自我控制的贡献。自动加入并允许退出的默认设计常能改变储蓄或参与率。" },
      misconceptions: ["行为经济学不是说人总是不理性，而是偏差在特定条件下具有可预测模式。", "助推不一定无害；选择架构也涉及透明度、操控和分配问题。"],
      examApplication: ["识别具体偏差及其如何改变传统模型预测。", "评价行为政策时比较有效性、自由、透明度和长期学习。"],
      summary: ["认知和自我控制限制会影响选择。", "框架与默认选项可改变行为。", "行为证据扩展而非简单替代传统经济模型。"],
      synonyms: ["有限理性", "助推", "认知偏差经济学"],
      explanation: "标准模型常把决策者视为信息充分、偏好稳定且能一致优化。行为研究通过实验和现实数据发现，损失厌恶、现状偏好、有限注意和社会规范会系统性影响选择。\n\n这些发现既用于解释，也用于政策设计。改变表格、提醒或默认选项可能改善结果，但政策制定者必须检验不同群体反应，并保护知情选择。",
    },
    en: {
      title: "Behavioural economics",
      takeaway: "Behavioural economics incorporates bounded rationality, self-control, and social preferences to explain systematic departures from a fully rational benchmark.",
      definition: "Behavioural economics combines psychology and economics to study how heuristics, biases, limited attention, self-control problems, and social preferences shape economic decisions.",
      causalChain: ["Decision-makers face complexity and cognitive limits", "They use shortcuts and respond to framing", "Observed choices depart from the standard rational benchmark", "Behavioural evidence informs richer models and policy design"],
      example: { title: "Default options change participation", explanation: "The 2017 Nobel Prize material summarises Richard Thaler's work on limited rationality, social preferences, and self-control. Automatic enrolment with an option to leave often changes saving or participation rates." },
      misconceptions: ["Behavioural economics does not claim that people are always irrational; it identifies predictable patterns under particular conditions.", "A nudge is not automatically benign; choice architecture raises questions of transparency, manipulation, and distribution."],
      examApplication: ["Identify a specific bias and show how it changes the standard model's prediction.", "Evaluate behavioural policy through effectiveness, freedom, transparency, and long-run learning."],
      summary: ["Cognitive and self-control limits affect choice.", "Framing and defaults can change behaviour.", "Behavioural evidence extends rather than simply replaces standard models."],
      synonyms: ["bounded rationality", "nudge", "behavioural bias"],
      explanation: "Standard models often represent agents as informed, consistent optimisers with stable preferences. Experiments and field evidence reveal systematic effects from loss aversion, status-quo bias, limited attention, and social norms.\n\nThe findings inform both explanation and intervention. A different form, reminder, or default can improve an outcome, but policymakers still need to test responses across groups and preserve informed choice.",
    },
  },
  {
    id: "u1-43-circular-economy",
    sourceUrl: "https://www.unep.org/circularity",
    prerequisites: ["u1-09-sustainability", "u1-11-interdependence"],
    related: ["u1-17-resource-allocation", "u1-20-government-intervention"],
    "zh-CN": {
      title: "相互依存与循环经济",
      takeaway: "循环经济把经济、社会与环境视为相互依存系统，通过减少材料投入、延长使用和回收价值来替代“开采—生产—丢弃”。",
      definition: "循环经济是一种设计和组织生产消费的框架，目标是减少资源开采和废弃物，在产品、部件和材料层级维持价值，并促进自然系统恢复。",
      causalChain: ["线性生产开采资源并产生废弃物", "设计减少材料并延长产品寿命", "维修、再用、再制造和回收形成闭环", "较低原生资源需求减轻生态压力并改变商业模式"],
      example: { title: "联合国环境署推动循环性", explanation: "联合国环境署的循环性工作把资源开采、气候、生物多样性和污染联系起来，强调产品设计、商业模式和公共政策需要协同，而不仅是末端回收。" },
      misconceptions: ["循环经济不等于只增加回收；优先级通常从避免、减量和再用开始。", "循环过程也使用能源和资源，不可能在所有材料上实现百分之百闭环。"],
      examApplication: ["从产品生命周期追踪资源、价值和废弃物流。", "评价时讨论设计激励、基础设施、消费者行为、反弹效应和公平转型。"],
      summary: ["经济活动依赖社会与自然系统。", "循环策略在废弃前保留产品和材料价值。", "实现循环需要企业、消费者和政府协作。"],
      synonyms: ["循环性", "闭环经济", "经济社会环境相互依存"],
      explanation: "线性模式从环境取出材料，生产、消费后把残余排回环境。循环框架尝试在设计阶段减少投入，让产品可维护、可共享、可再制造，并在最后回收材料。\n\n循环转型展示相互依存：企业需要回收网络和稳定标准，消费者需要便利与信息，政府可用产品责任、采购和定价政策改变激励。最终成效取决于全生命周期资源节约，而不是单一回收率。",
    },
    en: {
      title: "Interdependence and the circular economy",
      takeaway: "A circular economy treats the economy, society, and environment as interdependent systems and replaces take-make-dispose with lower material use, longer use, and retained value.",
      definition: "A circular economy is a framework for designing and organising production and consumption to reduce extraction and waste, retain value in products, components, and materials, and support regeneration of natural systems.",
      causalChain: ["Linear production extracts resources and generates waste", "Design reduces material use and extends product life", "Repair, reuse, remanufacture, and recycling create loops", "Lower primary-resource demand reduces ecological pressure and changes business models"],
      example: { title: "UN Environment Programme promotes circularity", explanation: "UNEP work on circularity links resource extraction to climate, biodiversity, and pollution. It emphasises coordinated product design, business models, and public policy rather than relying only on end-of-pipe recycling." },
      misconceptions: ["A circular economy is not simply more recycling; prevention, reduction, and reuse usually come first.", "Circular processes also use energy and resources, so a perfect loop for every material is not realistic."],
      examApplication: ["Trace resource, value, and waste flows across the whole product life cycle.", "Evaluate design incentives, infrastructure, consumer behaviour, rebound effects, and a just transition."],
      summary: ["Economic activity depends on social and natural systems.", "Circular strategies preserve product and material value before disposal.", "Firms, consumers, and governments must coordinate the transition."],
      synonyms: ["circularity", "closed-loop economy", "economy society environment interdependence"],
      explanation: "A linear model extracts material from the environment, produces and consumes, and returns residuals as waste. Circular design reduces inputs, makes products maintainable and shareable, supports remanufacture, and recovers materials at the end.\n\nThe transition demonstrates interdependence. Firms need collection networks and stable standards, consumers need convenience and information, and government can reshape incentives through producer responsibility, procurement, and pricing. Success depends on life-cycle resource savings rather than a recycling rate alone.",
    },
  },
];

writeTopics(topics);
