import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { listImplementedIds, loadKnowledgePoint, projectRoot, readYaml, contentRoot } from "./content-utils.mjs";

const allowIncomplete = process.argv.includes("--allow-incomplete");
const validatorArgs = [path.join(projectRoot, "scripts", "validate-content.mjs")];
if (allowIncomplete) validatorArgs.push("--allow-incomplete");
execFileSync(process.execPath, validatorArgs, { cwd: projectRoot, stdio: "inherit" });

const manifest = readYaml(path.join(contentRoot, "manifest.yaml"));
const points = listImplementedIds().map(loadKnowledgePoint);
const source = `/* Auto-generated by scripts/compile-content.mjs. Do not edit. */\n` +
  `import type { KnowledgePoint, ManifestEntry } from "../types/content";\n\n` +
  `export const manifestEntries = ${JSON.stringify(manifest.entries, null, 2)} as ManifestEntry[];\n\n` +
  `export const knowledgePoints = ${JSON.stringify(points, null, 2)} as KnowledgePoint[];\n`;

fs.mkdirSync(path.join(projectRoot, "src", "generated"), { recursive: true });
fs.writeFileSync(path.join(projectRoot, "src", "generated", "content.ts"), source);

const workerBundle = points.map((point) => ({ id: point.meta.id, content: point.content }));
fs.mkdirSync(path.join(projectRoot, "worker", "generated"), { recursive: true });
fs.writeFileSync(path.join(projectRoot, "worker", "generated", "knowledge.json"), `${JSON.stringify(workerBundle, null, 2)}\n`);

console.log(`Compiled ${points.length} knowledge point(s).`);

